DROP TABLE IF EXISTS public.test;

CREATE TABLE IF NOT EXISTS public.user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL 
        CHECK (email <> '')
        CONSTRAINT max_len_email CHECK (LENGTH(email) <= 100),
    password_hash TEXT NOT NULL 
        CHECK (password_hash <> '')
        CONSTRAINT max_len_password_hash CHECK (LENGTH(password_hash) <= 256)
);

CREATE TYPE genders AS ENUM ('Мужской', 'Женский');

CREATE TABLE IF NOT EXISTS public.profile
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL 
        REFERENCES public.user (id),
    name TEXT DEFAULT NULL
        CONSTRAINT max_len_name CHECK (LENGTH(name) <= 100),
    surname TEXT DEFAULT NULL
        CONSTRAINT max_len_surname CHECK (LENGTH(surname) <= 100),
    birthdate DATE DEFAULT NULL,
    gender genders DEFAULT NULL,    
    created_time TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_time TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
        CONSTRAINT updated_time_after_created_time CHECK (updated_time >= created_time)
);
