CREATE TABLE IF NOT EXISTS public.permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL
        REFERENCES public.user (id),
    tree_id BIGINT NOT NULL
        REFERENCES public.tree (id)
);